
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 19;
  public static final int AND = 29;
  public static final int LT = 22;
  public static final int OVER = 20;
  public static final int ELSE = 8;
  public static final int TRUTH = 33;
  public static final int PLUS = 17;
  public static final int OR = 28;
  public static final int RPAREN = 12;
  public static final int EQUAL = 25;
  public static final int NOTEQUAL = 26;
  public static final int SEMI = 9;
  public static final int WHILE = 5;
  public static final int NOT = 27;
  public static final int RCURLY = 16;
  public static final int GTEQUAL = 23;
  public static final int RETURN = 6;
  public static final int ERROR = 34;
  public static final int IF = 7;
  public static final int GT = 24;
  public static final int LPAREN = 11;
  public static final int ID = 31;
  public static final int NUM = 32;
  public static final int LCURLY = 15;
  public static final int COMMA = 10;
  public static final int EOF = 0;
  public static final int MINUS = 18;
  public static final int LSQUARE = 13;
  public static final int error = 1;
  public static final int ASSIGN = 30;
  public static final int RSQUARE = 14;
  public static final int BOOL = 4;
  public static final int INTEGER = 3;
  public static final int VOID = 2;
  public static final int LTEQUAL = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VOID",
  "INTEGER",
  "BOOL",
  "WHILE",
  "RETURN",
  "IF",
  "ELSE",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "LCURLY",
  "RCURLY",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LTEQUAL",
  "LT",
  "GTEQUAL",
  "GT",
  "EQUAL",
  "NOTEQUAL",
  "NOT",
  "OR",
  "AND",
  "ASSIGN",
  "ID",
  "NUM",
  "TRUTH",
  "ERROR"
  };
}

